config/routes.rb
# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

# In order to update the route map below,
# run `bundle exec annotate -r` after modifying this file
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :checks, except: [:show] do
    collection do
      post :supports, format: :json
    end
  end

  resources :notifications, except: [:show]

  devise_for :users
  root to: "pages#home"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#           supports_checks POST   /checks/supports(.:format)                                                               checks#supports
#                    checks GET    /checks(.:format)                                                                        checks#index
#                           POST   /checks(.:format)                                                                        checks#create
#                 new_check GET    /checks/new(.:format)                                                                    checks#new
#                edit_check GET    /checks/:id/edit(.:format)                                                               checks#edit
#                     check PATCH  /checks/:id(.:format)                                                                    checks#update
#                           PUT    /checks/:id(.:format)                                                                    checks#update
#                           DELETE /checks/:id(.:format)                                                                    checks#destroy
#             notifications GET    /notifications(.:format)                                                                 notifications#index
#                           POST   /notifications(.:format)                                                                 notifications#create
#          new_notification GET    /notifications/new(.:format)                                                             notifications#new
#         edit_notification GET    /notifications/:id/edit(.:format)                                                        notifications#edit
#              notification PATCH  /notifications/:id(.:format)                                                             notifications#update
#                           PUT    /notifications/:id(.:format)                                                             notifications#update
#                           DELETE /notifications/:id(.:format)                                                             notifications#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format)                                                        devise/confirmations#new
#         user_confirmation GET    /users/confirmation(.:format)                                                            devise/confirmations#show
#                           POST   /users/confirmation(.:format)                                                            devise/confirmations#create
#                      root GET    /                                                                                        pages#home
#         letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

app/models/notification.rb
# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Jeremy Lecour <jlecour@evolix.fr>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)
# == Schema Information
#
# Table name: notifications
#
#  id           :bigint(8)        not null, primary key
#  channel      :integer          default("email"), not null
#  checks_count :integer          default(0), not null
#  interval     :integer          not null
#  label        :string(255)
#  recipient    :string(255)      not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  check_id     :bigint(8)
#  user_id      :bigint(8)
#
# Indexes
#
#  index_notifications_on_check_id  (check_id)
#  index_notifications_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (check_id => checks.id)
#  fk_rails_...  (user_id => users.id)
#

class Notification < ApplicationRecord
  belongs_to :user
  has_many :check_notifications, dependent: :destroy
  has_many :checks, -> { order(domain_expires_at: :asc) }, through: :check_notifications

  enum channel: [:email]

  validates :channel, presence: true
  validates :interval, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :recipient, presence: true

  def notifical_label
    return label if label.present?

    "#{recipient} (#{interval})"
  end
end

app/controllers/notifications_controller.rb
# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Jeremy Lecour <jlecour@evolix.fr>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notification, except: [:index, :new, :create]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    @notifications = policy_scope(Notification).order(checks_count: :desc)
  end

  def new
    @notification = Notification.new
    authorize @notification
    @notification.recipient = current_user.email
  end

  def create
    @notification = Notification.new(notification_params)
    @notification.user = current_user
    authorize @notification

    if @notification.save
      flash[:notice] = t("notifications.created", scope: :flashes)
      redirect_to notifications_path
    else
      flash.now[:alert] = t("notifications.invalid", scope: :flashes)
      render :new
    end
  end

  def edit; end

  def update
    if @notification.update(notification_params)
      flash[:notice] = t("notifications.updated", scope: :flashes)
      redirect_to notifications_path
    else
      flash.now[:alert] = t("notifications.error", scope: :flashes)
      render :edit
    end
  end

  def destroy
    @notification.destroy!

    flash[:notice] = t("notifications.destroyed", scope: :flashes)
    redirect_to notifications_path
  end

  private

  def set_notification
    @notification = Notification.find(params[:id])
    authorize @notification
  end

  def notification_params
    params.require(:notification).permit(:label, :recipient, :interval)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def many_channels_available?
    Notification.channels.many?
  end

  def notification_variable_col_class
    many_channels_available? ? "col-md-4" : "col-md-5"
  end
end

app/views/notifications/_form.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<%= simple_form_for(notification) do |f| %>
  <%= f.input :recipient, as: :email,
                          input_html: { autocapitalize: :none, autocorrect: :off }
      %>

  <%= f.input :interval, as: :integer, required: true %>

  <%= f.input :label, hint: t(".label_hint") %>

  <%= f.button :submit, class: "btn-primary mt-3" %>
<% end %>

app/views/notifications/_nested_form.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Jeremy Lecour <jlecour@evolix.fr>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<fieldset class="form-group">
  <div class="form-row">
    <%- if many_channels_available? %>
      <div class="form-group col-md-2">
        <%- if f.object.new_record? -%>
          <%= f.input :channel, collection: Notification.channels.keys, label: false %>
        <% else -%>
          <%= f.input_field :channel, as: :string, readonly: true, class: "form-control-plaintext" %>
        <%- end %>
      </div>
    <% end %>

    <div class="form-group <%= notification_variable_col_class %>">
      <%= f.input :recipient, as: :email, label: false %>
    </div>

    <div class="form-group col-md-2">
      <%= f.input :interval, as: :integer, label: false, required: true %>
    </div>

    <div class="form-group <%= notification_variable_col_class %>">
      <%= f.input :label, label: false %>
    </div>
  </div>
</fieldset>

app/views/notifications/_nested_form_headers.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Jeremy Lecour <jlecour@evolix.fr>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="form-row">
  <%- if many_channels_available? %>
    <div class="col-md-2">
      <%= f.label :channel %>
    </div>
  <% end %>

  <div class="<%= notification_variable_col_class %>">
    <%= f.label :recipient %>
  </div>

  <div class="col-md-2">
    <%= f.label :interval, required: true %>
  </div>

  <div class="<%= notification_variable_col_class %>">
    <%= f.label :label %>
  </div>
</div>

app/views/notifications/_table.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="mb-4 table-responsive">
  <table class="table notifications-table">
    <thead>
      <tr>
        <th scope="col">
          <%= Notification.human_attribute_name("label") %>
        </th>
        <th scope="col">
          <%= Notification.human_attribute_name("recipient") %>
        </th>
        <th scope="col">
          <%= Notification.human_attribute_name("interval") %>
        </th>
        <th scope="col">
          <%= Notification.human_attribute_name("checks_count") %>
        </th>
        <th scope="col" class="text-right"><%= t(".th.edit") %></th>
      </tr>
    </thead>
    <tbody>
      <% notifications.each do |notification| %>
        <tr class="notification-row">
          <td>
            <strong><%= notification.label %></strong>
          </td>
          <td>
            <%= notification.recipient %>
          </td>
          <td>
            <%= t(".interval_in_days", count: notification.interval) %>
          </td>
          <td>
            <%= notification.checks_count %>
          </td>
          <td class="action text-right">
            <%= link_to edit_notification_path(notification), "data-turbolinks" => false do %>
              <%== Octicons::Octicon.new("pencil").to_svg %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/notifications/edit.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">
      <h1><%= t(".title") %></h1>

      <%= render "form", notification: @notification %>
    </div>
  </div>

  <div class="row mt-5 justify-content-center">
    <div class="col-12 col-lg-10">
      <h4><%= t(".checks", count: @notification.checks_count) %></h4>
      <% if @notification.checks_count.positive? %>
        <%= render "checks/table", checks: @notification.checks, skip_sort: true, skip_pagination: true %>
      <% end %>
    </div>
  </div>

  <div class="row mt-5 mb-3 justify-content-center">
    <div class="col-12 col-lg-10">
      <%= button_to(t("helpers.submit.notification.delete"), notification_path(@notification), class: "btn btn-danger", method: :delete,
            data: { confirm: t(".destroy_confirmation", count: @notification.checks_count) }) %>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10 col-xl-9">
      <% if @notifications.empty? %>
        <div class="alert alert-info">
          <%= t(".no_notification_yet_html", new_path: new_notification_path) %>
        </div>
      <% else %>
        <div class="row justify-content-md-end">
          <%= link_to("Ajouter une notification", new_notification_path, class: "btn btn-primary") %>
        </div>
        <h1 class="mb-3 mb-sm-5"><%= t(".title") %></h1>
        <%= render "table", notifications: @notifications %>
      <% end %>
      <div class="bd-callout bd-callout-info">
        <p><%= t(".explanation") %></p>
      </div>
    </div>
  </div>
</div>

app/views/notifications/new.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">
      <h1><%= t(".title") %></h1>

      <%= render "form", notification: @notification %>
    </div>
  </div>
</div>