config/routes.rb
# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

# In order to update the route map below,
# run `bundle exec annotate -r` after modifying this file
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :checks, except: [:show] do
    collection do
      post :supports, format: :json
    end
  end

  resources :notifications, except: [:show]

  devise_for :users
  root to: "pages#home"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#           supports_checks POST   /checks/supports(.:format)                                                               checks#supports
#                    checks GET    /checks(.:format)                                                                        checks#index
#                           POST   /checks(.:format)                                                                        checks#create
#                 new_check GET    /checks/new(.:format)                                                                    checks#new
#                edit_check GET    /checks/:id/edit(.:format)                                                               checks#edit
#                     check PATCH  /checks/:id(.:format)                                                                    checks#update
#                           PUT    /checks/:id(.:format)                                                                    checks#update
#                           DELETE /checks/:id(.:format)                                                                    checks#destroy
#             notifications GET    /notifications(.:format)                                                                 notifications#index
#                           POST   /notifications(.:format)                                                                 notifications#create
#          new_notification GET    /notifications/new(.:format)                                                             notifications#new
#         edit_notification GET    /notifications/:id/edit(.:format)                                                        notifications#edit
#              notification PATCH  /notifications/:id(.:format)                                                             notifications#update
#                           PUT    /notifications/:id(.:format)                                                             notifications#update
#                           DELETE /notifications/:id(.:format)                                                             notifications#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format)                                                        devise/confirmations#new
#         user_confirmation GET    /users/confirmation(.:format)                                                            devise/confirmations#show
#                           POST   /users/confirmation(.:format)                                                            devise/confirmations#create
#                      root GET    /                                                                                        pages#home
#         letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

app/views/shared/_beta_banner.html.erb
<div class="container-fluid beta-banner">
  <p><%= t(".beta_info")%> <%= link_to(t(".issue_link"),("https://github.com/Evolix/chexpire/issues/new"))%>
  </p>
</div>

app/views/shared/_devise_form_container.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">
      <%= yield :devise_form_content %>
    </div>
  </div>
</div>

app/views/shared/_home_header.html.erb
<div class="container-fluid header">
    <div class="d-flex justify-content-center">
        <div class="d-flex flex-wrap justify-content-center flex-column align-items-center">
            <div class="d-flex flex-wrap justify-content-center flex-column align-items-center">
                <h1><%= t(".welcome") %></h1>
                <p><%= t(".intro") %></p>
            </div>
            <div class="d-flex flex-wrap justify-content-around align-items-center">
                <%= link_to t(".actions.learn_more"), root_path(@root, anchor: "description"), :class => "btn btn-primary" %>
                <%= link_to t(".actions.sign_up"), new_user_registration_path, :class => "btn btn-tertiary" %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<nav class="navbar navbar-expand-lg navbar-dark justify-content-between">
  <div class="container-fluid">
    <%= link_to (user_signed_in? ? checks_path : root_path), class: "navbar-brand" do %>
      <%= image_tag 'chexpire10.png', width: 200, alt: 'chexpire logo' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to(t(".my_checks"), checks_path, class: "nav-link") %>
          </li>
          <li class="nav-item">
            <%= link_to(t(".new_domain_check"), new_check_path(kind: :domain), class: "nav-link") %>
          </li>
          <li class="nav-item">
            <%= link_to(t(".new_ssl_check"), new_check_path(kind: :ssl), class: "nav-link") %>
          </li>
          <li class="nav-item">
            <%= link_to(t(".my_notifications"), notifications_path, class: "nav-link") %>
          </li>
          <li class="nav-item">
            <%= link_to("GitHub", "https://github.com/Evolix/chexpire", class: "nav-link") %>
          </li>
        <% end %>
      </ul>

      <div class="my-2 my-lg-0">
        <% if user_signed_in? %>
          <div class="navbar-item">
            <div class="dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.email %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                  <i class="fa fa-user"></i>
                  <%= t(".profile", default: "Profile") %>
                <% end %>

                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <i class="fa fa-sign-out"></i>
                  <%= t(".sign_out", default: "Sign out") %>
                <% end %>
              </div>
            </div>
          </div>
        <% else %>
          <!-- Login link (when logged out) -->
          <%= link_to t(".sign_in"), new_user_session_path, class: "navbar-item navbar-link" %>
          <%= link_to t(".sign_up"), new_user_registration_path, class: "navbar-item navbar-link" %>
          <%= link_to "GitHub", "https://github.com/Evolix/chexpire", class: "navbar-item navbar-link" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">
      <% if notice.present? %>
        <div class="alert alert-success alert-layout" role="alert"><%= notice %></div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-danger alert-layout" role="alert"><%= alert %></div>
      <% end %>
    </div>
  </div>
</div>