config/routes.rb
# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

# In order to update the route map below,
# run `bundle exec annotate -r` after modifying this file
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :checks, except: [:show] do
    collection do
      post :supports, format: :json
    end
  end

  resources :notifications, except: [:show]

  devise_for :users
  root to: "pages#home"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#           supports_checks POST   /checks/supports(.:format)                                                               checks#supports
#                    checks GET    /checks(.:format)                                                                        checks#index
#                           POST   /checks(.:format)                                                                        checks#create
#                 new_check GET    /checks/new(.:format)                                                                    checks#new
#                edit_check GET    /checks/:id/edit(.:format)                                                               checks#edit
#                     check PATCH  /checks/:id(.:format)                                                                    checks#update
#                           PUT    /checks/:id(.:format)                                                                    checks#update
#                           DELETE /checks/:id(.:format)                                                                    checks#destroy
#             notifications GET    /notifications(.:format)                                                                 notifications#index
#                           POST   /notifications(.:format)                                                                 notifications#create
#          new_notification GET    /notifications/new(.:format)                                                             notifications#new
#         edit_notification GET    /notifications/:id/edit(.:format)                                                        notifications#edit
#              notification PATCH  /notifications/:id(.:format)                                                             notifications#update
#                           PUT    /notifications/:id(.:format)                                                             notifications#update
#                           DELETE /notifications/:id(.:format)                                                             notifications#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format)                                                        devise/confirmations#new
#         user_confirmation GET    /users/confirmation(.:format)                                                            devise/confirmations#show
#                           POST   /users/confirmation(.:format)                                                            devise/confirmations#create
#                      root GET    /                                                                                        pages#home
#         letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

app/models/check.rb
# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Jeremy Lecour <jlecour@evolix.fr>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)
# == Schema Information
#
# Table name: checks
#
#  id                   :bigint(8)        not null, primary key
#  active               :boolean          default(TRUE), not null
#  comment              :string(255)
#  consecutive_failures :integer          default(0), not null
#  domain               :string(255)      not null
#  domain_created_at    :datetime
#  domain_expires_at    :datetime
#  domain_updated_at    :datetime
#  kind                 :integer          not null
#  last_run_at          :datetime
#  last_success_at      :datetime
#  mode                 :integer          default("auto"), not null
#  round_robin          :boolean          default(TRUE)
#  vendor               :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  user_id              :bigint(8)
#
# Indexes
#
#  index_checks_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Check < ApplicationRecord
  belongs_to :user
  has_many :logs, class_name: "CheckLog", dependent: :destroy
  has_many :check_notifications, dependent: :destroy
  has_many :notifications, -> { order(checks_count: :desc) },
                          through: :check_notifications, validate: true

  accepts_nested_attributes_for :notifications,
    reject_if: lambda { |att| att["interval"].blank? }

  enum kind: [:domain, :ssl]
  enum mode: [:auto, :manual]

  # Those dates are written as UTC,
  # but not converted back when read from the database
  self.skip_time_zone_conversion_for_attributes = [
    :domain_created_at,
    :domain_updated_at,
    :domain_expires_at,
  ]

  validates :kind, presence: true
  validates :domain, presence: true
  validate :domain_created_at_past
  validate :domain_updated_at_past
  validates :domain_expires_at, presence: true, unless: :supported?
  validates :comment, length: { maximum: 255 }
  validates :vendor, length: { maximum: 255 }

  before_save :reset_consecutive_failures
  before_save :set_mode
  after_update :reset_check_notifications
  after_save :enqueue_sync

  scope :active, -> { where(active: true) }
  scope :last_run_failed, -> {
    where("(last_success_at IS NULL AND last_run_at IS NOT NULL)
      OR (last_success_at <= DATE_SUB(last_run_at, INTERVAL 5 MINUTE))")
  }

  scope :kind, ->(kind) { where(kind: kind) }
  scope :by_domain, ->(domain) { where("domain LIKE ?", "%#{domain}%") }
  scope :consecutive_failures, ->(consecutive) {
    where("consecutive_failures >= ?", consecutive)
  }

  def self.default_sort
    [:domain_expires_at, :asc]
  end

  def days_from_last_success
    return unless last_success_at.present?

    # return the number of whole days
    ((Time.now - last_success_at) / (24 * 3600)).to_i
  end

  def increment_consecutive_failures!
    self.consecutive_failures += 1
    save!(validate: false)
  end

  def supported?
    return true unless domain?
    return true if domain.blank?

    begin
      Whois::Parser.for(domain)
      true
    rescue Whois::UnsupportedDomainError
      false
    rescue StandardError
      false
    end
  end

  def domain_expires_in_days
    Integer(domain_expires_at.to_date - Time.now.utc.to_date)
  end

  private

  def domain_created_at_past
    errors.add(:domain_created_at, :past) if domain_created_at.present? && domain_created_at.future?
  end

  def domain_updated_at_past
    errors.add(:domain_updated_at, :past) if domain_updated_at.present? && domain_updated_at.future?
  end

  def enqueue_sync
    return unless active?
    return unless saved_changes.key?("domain")

    ResyncJob.perform_later(id)
  end

  def reset_check_notifications
    return unless (saved_changes.keys & %w[domain domain_expires_at]).present?

    check_notifications.each(&:reset!)
  end

  def reset_consecutive_failures
    return unless last_success_at_changed? || mode_changed? || domain_changed?
    return if consecutive_failures_changed?

    self.consecutive_failures = 0
  end

  def set_mode
    return unless domain_changed?
    self.mode = supported? ? :auto : :manual
  end
end

app/controllers/checks_controller.rb
# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Jeremy Lecour <jlecour@evolix.fr>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

class ChecksController < ApplicationController # rubocop:disable Metrics/ClassLength
  before_action :authenticate_user!
  before_action :set_check, except: [:index, :new, :create, :supports]
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  has_scope :kind
  has_scope :by_domain
  has_scope :recurrent_failures, type: :boolean do |_controller, scope, _value|
    scope.consecutive_failures(Rails.configuration.chexpire.interface.consecutive_failures_as_error)
  end

  def index
    @checks = apply_scopes(policy_scope(Check)).order(Hash[*current_sort]).page(params[:page])
  end

  def new
    @check = Check.new
    authorize @check

    if params[:kind].present?
      return not_found unless Check.kinds.key?(params[:kind])
      @check.kind = params[:kind]
    end

    build_empty_notification
  end

  def create # rubocop:disable Metrics/AbcSize
    @check = Check.new(new_check_params.merge(user: current_user))
    authorize @check

    if @check.save
      flash[:notice] = t("checks.created", scope: :flashes)
      redirect_to checks_path
    else
      flash.now[:alert] = t("checks.invalid", scope: :flashes)

      fill_or_build_new_notification
      render :new
    end
  end

  def edit
    build_empty_notification
  end

  def update
    if @check.update(update_check_params)
      flash[:notice] = t("checks.updated", scope: :flashes)
      redirect_to checks_path
    else
      flash.now[:alert] = t("checks.invalid", scope: :flashes)

      fill_or_build_new_notification
      render :edit
    end
  end

  def destroy
    @check.destroy!

    flash[:notice] = t("checks.destroyed", scope: :flashes)
    redirect_to checks_path
  end

  def supports
    @check = Check.new(new_check_params)
    authorize @check
  end

  private

  def set_check
    @check = Check.find(params[:id])
    authorize @check
  end

  def new_check_params
    check_params(:kind)
  end

  def update_check_params
    check_params(:active)
  end

  def check_params(*others)
    permitted = params.require(:check)
                      .permit(:domain, :domain_expires_at, :comment, :vendor,
                              :round_robin, *others,
                              notification_ids: [],
                              notifications_attributes: [:channel, :label, :recipient, :interval])

    merge_current_user!(permitted)

    permitted
  end

  def merge_current_user!(permitted)
    return unless permitted[:notifications_attributes].present?

    permitted[:notifications_attributes].each_pair do |_key, attributes|
      attributes.merge!(user: current_user)
    end
  end

  def build_empty_notification
    @new_notification = @check.notifications.build
    @new_notification.recipient = current_user.email
  end

  def fill_or_build_new_notification
    last_notification = @check.notifications.last

    # user has filled a new notification: we use it for the form
    if last_notification.present? && last_notification.new_record?
      @new_notification = last_notification
    else # otherwise, set a new empty notification
      build_empty_notification
    end
  end

  def current_sort
    @current_sort ||= clean_sort || Check.default_sort
  end
  helper_method :current_sort

  def clean_sort
    return unless params[:sort].present?
    field, _, direction = params[:sort].rpartition("_").map(&:to_sym)

    valid_fields = [:domain, :domain_expires_at]
    valid_directions = [:asc, :desc]

    return unless valid_fields.include?(field)
    return unless valid_directions.include?(direction)

    [field, direction]
  end
end

app/helpers/checks_helper.rb
# Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr>
# License: GNU AGPL-3+ (see full text in LICENSE file)

# frozen_string_literal: true

module ChecksHelper
  def check_row_class(check)
    expiry_date = check.domain_expires_at

    return unless expiry_date.present?

    return "table-danger" if expiry_date <= 3.days.from_now
    return "table-warning" if expiry_date < 1.month.from_now
  end

  def checks_sort_links(field)
    %i[asc desc].map { |direction|
      checks_sort_link(field, direction)
    }.join
  end

  def checks_sort_link(field, direction)
    classes = "btn btn-light btn-sm mx-1 mx-1 px-1 py-0"
    sort = [field, direction]

    icon = direction == :asc ? "chevron-up" : "chevron-down"
    html = Octicons::Octicon.new(icon).to_svg.html_safe

    sort_path = checks_path(current_criterias.merge(sort: sort.join("_")))
    link_to_unless sort == current_sort, html, sort_path, class: classes do
      content_tag(:span, html, class: classes + " active")
    end
  end

  def check_in_error?(check)
    check.consecutive_failures >=
      Rails.configuration.chexpire.interface.consecutive_failures_as_error
  end

  def check_error(check)
    content_tag(
      :span,
      Octicons::Octicon.new("alert", class: "ml-1").to_svg.html_safe,
      class: "in-error text-danger",
      data: {
        toggle: "tooltip",
        placement: "bottom",
        title: check_last_success_title(check),
      },
    )
  end

  def current_criterias
    current_scopes.merge(sort: params[:sort])
  end

  def scoped_with?(scope)
    name, value = scope.first
    scope_value = current_scopes[name]
    scope_value = scope_value.to_sym if scope_value.respond_to?(:to_sym)

    scope_value == value
  end

  def check_button_criterias(scope)
    if scoped_with?(scope)
      current_criterias.except(scope.keys.first)
    else
      current_criterias.merge(scope)
    end
  end

  def check_button_scope_class(scope = nil)
    "btn btn-sm " + if scope && scoped_with?(scope)
                      "btn-info active"
                    else
                      "btn-outline-info"
                    end
  end

  def check_last_success_title(check)
    return t(".never_succeeded") if check.last_success_at.nil?

    t(".days_from_last_success", count: check.days_from_last_success)
  end
end

app/views/checks/_filters.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="row justify-content-md-end checks-filters">

  <div class="col-md-6 mb-3 d-flex justify-content-between justify-content-md-start">
    <div class="btn-group mr-2">
      <% Check.kinds.keys.map(&:to_sym).each do |kind_name| %>
        <%= link_to t(".kind_#{kind_name}"),
            checks_path(check_button_criterias(kind: kind_name)),
            class: check_button_scope_class(kind: kind_name) + " " + kind_name.to_s %>
      <% end %>
    </div>

    <%= link_to t(".with_error"),
        checks_path(check_button_criterias(recurrent_failures: true)),
        class: check_button_scope_class(recurrent_failures: true) + " with_error" %>
  </div>

  <div class="col-md-6 mb-3">
    <%= form_tag(checks_path, method: :get) do %>
      <div class="form-row justify-content-around">
        <div class="col">
          <div class="input-group">
            <%= search_field_tag :by_domain, current_scopes[:by_domain], class: "form-control form-control-sm", placeholder: ".com, example.org, …" %>
            <div class="input-group-append">
              <%= button_tag Octicons::Octicon.new("search").to_svg.html_safe, class: "btn btn-sm btn-outline-secondary" %>
            </div>
          </div>

          <%- current_criterias.except(:by_domain).compact.each_pair do |name, value| %>
            <%= hidden_field_tag name, value%>
          <% end %>
        </div>

        <div class="col-auto">
          <%= link_to Octicons::Octicon.new("x").to_svg.html_safe, checks_path, class: "btn btn-sm btn-outline-danger" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/checks/_form.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<%= simple_form_for(check) do |f| %>
  <%= f.input :domain,
        autofocus: true,
        input_html: { autocapitalize: :none, autocorrect: :off, data: { kind: check.kind } },
        label: t(".#{check.kind || "generic" }.domain"),
        hint: t(".#{check.kind || "generic" }.unsupported"),
        hint_html: {
          id: "check_domain_unsupported_container",
          class: "#{check.supported? && 'd-none'}",
        }
    %>

  <% if check.new_record? %>
    <%= f.input :kind, as: check.kind.present? ? :hidden : :radio_buttons, collection: Check.kinds.keys %>
  <% end %>

  <div id="check_domain_expires_at_container" class="<%= check.supported? ? "d-none" : "d-block" %>">
    <%= f.input :domain_expires_at,
                required: true,
                input_html: {
                  type: :date,
                  value: check.domain_expires_at&.to_date,
                  min: Date.yesterday,
                  max: 10.years.from_now.end_of_year.to_date
                },
                as: :string,
                placeholder: t(".domain_expires_at_placeholder")
    %>
  </div>

  <%= f.input :comment %>
  <%= f.input :vendor %>

  <% if check.ssl? %>
    <%= f.input :round_robin %>
  <% end %>

  <% if check.persisted? %>
    <%= f.input :active %>
  <% end %>

  <p class="mt-5 bd-callout bd-callout-info"><%= t(".notifications_hint") %></p>

  <%= f.association :notifications, as: :check_boxes,
                    collection: policy_scope(Notification),
                    label_method: :notifical_label,
                    label_text: false %>

  <%= f.fields_for :notifications, new_notification do |nf| %>
    <%= render "notifications/nested_form_headers", f: nf %>
    <%= render "notifications/nested_form", f: nf, notification: new_notification %>
  <% end %>

  <%= f.button :submit, class: "btn-primary mt-5" %>
<% end %>

app/views/checks/_table.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="mb-4 table-responsive">
  <table class="table checks-table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">
          <%= t(".th.domain") %>
          <% unless defined?(skip_sort) %>
            <span class="sort-links mx-sm-2 text-nowrap">
              <%== checks_sort_links(:domain) %>
            </span>
          <% end %>
        </th>
        <th scope="col">
          <span class="d-none d-sm-inline"><%= t(".th.expiry_date") %></span>
          <span class="d-inline d-sm-none"><%= t(".th.expiry_date_short") %></span>
          <% unless defined?(skip_sort) %>
            <span class="sort-links mx-sm-2 text-nowrap">
              <%== checks_sort_links(:domain_expires_at) %>
            </span>
          <% end %>
        </th>
        <th scope="col" class="text-right"><%= t(".th.edit") %></th>
      </tr>
    </thead>
    <tbody>
      <% checks.each do |check| %>
        <tr class="check-row <%= check_row_class(check) %>">
          <td class="kind">
            <span class="badge badge-info <%=check.kind%>"><%= t(".kind_labels.#{check.kind}") %></span>
          </td>
          <td>
            <%= check_error(check) if check_in_error?(check) %>
            <strong><%= check.domain %></strong>
          </td>
          <td>
            <% if check.domain_expires_at.present? %>
              <%= content_tag :span, format_date(check.domain_expires_at), class: "d-none d-md-inline" %>
              <%= content_tag :span, format_date(check.domain_expires_at, format: :short), class: "d-inline d-md-none" %>
            <% end %>
          </td>
          <td class="action text-right">
            <%= link_to edit_check_path(check), "data-turbolinks" => false do %>
              <%== Octicons::Octicon.new("pencil").to_svg %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate checks unless defined?(skip_pagination)%>

app/views/checks/edit.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">
      <h1><%= t(".title") %></h1>

      <%= render "form", check: @check, new_notification: @new_notification %>
    </div>
  </div>

  <div class="row mt-5 justify-content-center">
    <div class="col-12 col-lg-10">
      <%= button_to(t("helpers.submit.check.delete"), check_path(@check), class: "btn btn-danger", method: :delete,
            data: { confirm: t(".destroy_confirmation") }) %>
    </div>
  </div>
</div>

app/views/checks/index.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10 col-xl-9">
      <% if @checks.empty? && current_scopes.blank? %>
        <div class="alert alert-info">
          <%= t(".no_check_yet_html", new_domain_path: new_check_path(kind: :domain), new_ssl_path: new_check_path(kind: :ssl)) %>
        </div>
      <% else %>
        <h1 class="mb-3 mb-sm-5"><%= t(".title") %></h1>

        <%= render "filters" %>

        <% if @checks.any? %>
          <%= render "table", checks: @checks %>
        <% else %>
          <div class="alert alert-warning"><%= t(".no_matching_check") %></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/checks/new.html.erb
<% # Copyright (C) 2018 Colin Darie <colin@darie.eu>, 2018 Evolix <info@evolix.fr> %>
<% # License: GNU AGPL-3+ (see full text in LICENSE file) %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-10">
      <h1><%= t(".#{@check.kind}.title") %></h1>

      <%= render "form", check: @check, new_notification: @new_notification %>
    </div>
  </div>
</div>